language: node_js
node_js:
  - "8"

before_install:
  - unset _JAVA_OPTIONS # To suppress a warning from Java to stderr
  - pip install git+https://github.com/lbl-srg/modelica-buildings@master

install:
  - make install
  - make compile
  - make test-moParser

script:
  - make test
