language: node_js
node_js:
  - "8"

env:
  - MODELICAPATH="./.temp/"

before_install:
  - unset _JAVA_OPTIONS # To suppress a warning from Java to stderr

install:
  - git clone --branch=master https://github.com/lbl-srg/modelica-buildings ./.temp/
  - make install
  - make compile
  - make test-moParser

script:
  - make test
